apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  namespace: tds-group-3
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: 172786533418.dkr.ecr.us-east-2.amazonaws.com/tds-group-3/location:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: location-config
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: location-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: location-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
