apiVersion: v1
kind: Secret
metadata:
  name: location-secret
  namespace: tds-group-3
type: Opaque
stringData:
  MONGODB_URI: "${LOCATION_MONGODB_URI}"
  JWT_SECRET: "${JWT_SECRET}"
  LOKI_URL: "${LOKI_URL}"
  LOKI_USER: "${LOKI_USER}"
  LOKI_TOKEN: "${LOKI_TOKEN}"
