apiVersion: v1
kind: Service
metadata:
  name: location
  namespace: tds-group-3
  labels:
    app: location
spec:
  type: ClusterIP
  selector:
    app: location
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
