name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:coverage

      - name: Upload unit coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: udesa-software/location
          files: ./coverage/lcov.info
          flags: unit
          fail_ci_if_error: true

      - name: Run integration tests
        run: npm run test:integration:coverage

      - name: Upload integration coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: udesa-software/location
          files: ./coverage-integration/lcov.info
          flags: integration
          fail_ci_if_error: true
